# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :upload_lane do
  upload_symbols_to_bugsnag(
    config_file: "/Users/matthew.howells/Documents/Test-Projects/Cocoa/IOS/FastLanePlatTesting/fastlane-test/fastlane-test/Info.plist",
    dsym_path: "/Users/matthew.howells/Library/Developer/Xcode/DerivedData/fastlane-test-gjxprteyygvaoaavkocjovbzfpoq/Build/Products/Debug-iphonesimulator/fastlane-test.app.dSYM",
  )
  end
  lane :build_lane do
  send_build_to_bugsnag(
    config_file: "/Users/matthew.howells/Documents/Test-Projects/Cocoa/IOS/FastLanePlatTesting/fastlane-test/fastlane-test/Info.plist",
    api_key: "91b91acefad3652c939706e5ae1c2450",
    app_version: "13.0.0",
    builder: "matth-bugsnag",
    repository: "https://github.com/matth-bugsnag/fastlane-test",
    metadata: {"test1": "First test", "test2": "Second test", "test3": "Third test"},
    revision: "1df59bb",
    provider: "github",
    release_stage: "Production",
    ios_bundle_version: "1",
  )
  end
end